### ISSUE TITLE
Issue with reading sensors

### ISSUE THREAD

**Issue by alex-dow** [psistats/linux-client#21]
```
# psistats sensors
acpitz-virtual-0.temp1  (25.0 *C)
Traceback (most recent call last):
  File "/usr/bin/psistats", line 9, in <module>
    load_entry_point('psistats===0.2.0develop', 'console_scripts', 'psistats')()
  File "/usr/lib/python2.7/dist-packages/psistats/cli.py", line 153, in main
    list_sensors()
  File "/usr/lib/python2.7/dist-packages/psistats/cli.py", line 123, in list_sensors
    sys.stdout.write('%s.%s  (%s %s)\n' % (confKey, feature.label, feature.get_value(), unit))
  File "/usr/lib/python2.7/dist-packages/psistats/libsensors/lib/sensors.py", line 155, in get_value
    return next(iter(self)).get_value()
  File "/usr/lib/python2.7/dist-packages/psistats/libsensors/lib/sensors.py", line 106, in get_value
    _get_value(byref(self.parent.chip), self.number, byref(result))
  File "/usr/lib/python2.7/dist-packages/psistats/libsensors/lib/sensors.py", line 42, in _error_check
    raise SensorsError(_strerror(result), result)
psistats.libsensors.lib.sensors.SensorsError: Can't read
```

```
# sensors -u
acpitz-virtual-0
Adapter: Virtual device
temp1:
  temp1_input: 25.000
  temp1_crit: 107.000

radeon-pci-0100
Adapter: PCI adapter
temp1:
ERROR: Can't get value of subfeature temp1_input: Can't read
  temp1_crit: 120.000
  temp1_crit_hyst: 90.000

coretemp-isa-0000
Adapter: ISA adapter
Physical id 0:
  temp1_input: 46.000
  temp1_max: 84.000
  temp1_crit: 100.000
  temp1_crit_alarm: 0.000
Core 0:
  temp2_input: 44.000
  temp2_max: 84.000
  temp2_crit: 100.000
  temp2_crit_alarm: 0.000
Core 1:
  temp3_input: 43.000
  temp3_max: 84.000
  temp3_crit: 100.000
  temp3_crit_alarm: 0.000
Core 2:
  temp4_input: 45.000
  temp4_max: 84.000
  temp4_crit: 100.000
  temp4_crit_alarm: 0.000
Core 3:
  temp5_input: 41.000
  temp5_max: 84.000
  temp5_crit: 100.000
  temp5_crit_alarm: 0.000

i8k-virtual-0
Adapter: Virtual device
fan2:
  fan2_input: 3228.000
temp1:
  temp1_input: 45.000
temp2:
  temp2_input: 49.000
temp3:
  temp3_input: 32.000
temp4:
ERROR: Can't get value of subfeature temp4_input: Can't read
```

Ubuntu 15.04

Seems that only some sensors can't be read by libsensor, which raises the exception. Looks like it's an exception we can ignore (or at least, log somewhere).

**Comment by alex-dow** [comment]
The code around sensors has been changed, hopefully for the better.

It now throws a CantReadSensor exception in this case. CantReadSensor still needs to be caught and logged and kill the sensor reporting thread.

**Comment by alex-dow** [comment]
```
# psistats sensors
acpitz-virtual-0.temp1  (25.0 *C)
Traceback (most recent call last):
  File "/usr/bin/psistats", line 9, in <module>
    load_entry_point('psistats===0.2.0develop', 'console_scripts', 'psistats')()
  File "/usr/lib/python2.7/dist-packages/psistats/cli.py", line 153, in main
    list_sensors()
  File "/usr/lib/python2.7/dist-packages/psistats/cli.py", line 123, in list_sensors
    sys.stdout.write('%s.%s  (%s %s)\n' % (confKey, feature.label, feature.get_value(), unit))
  File "/usr/lib/python2.7/dist-packages/psistats/libsensors/lib/sensors.py", line 155, in get_value
    return next(iter(self)).get_value()
  File "/usr/lib/python2.7/dist-packages/psistats/libsensors/lib/sensors.py", line 106, in get_value
    _get_value(byref(self.parent.chip), self.number, byref(result))
  File "/usr/lib/python2.7/dist-packages/psistats/libsensors/lib/sensors.py", line 42, in _error_check
    raise SensorsError(_strerror(result), result)
psistats.libsensors.lib.sensors.SensorsError: Can't read
```

Also have to handle this problem when running psistats sensors
